[package]
name = "mdpdf"
version = "1.8.0"
edition = "2024"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
comrak = "0.52.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0.102"
lopdf = "0.40.0"
headless_chrome = "1.0.21"
clap = { version = "4", feature = ["derive"] }
url = "2.5.8"
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
dirs = "6"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true